name: RyanRhoten
favicon: null
layout_spectrum: 0.93116
typography_spectrum: 0.62328
title: I help business professionals Build Your Brand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#178d96'
    - '#ffffff'
    - '#ef812f'
    - '#8bc6ca'
    - '#343432'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
